Preparing training and test sets...
Creating samples using as look_back = 15
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 127, in <module>
    x, y, transactions = create_dataset(bonifici, 15)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 70, in create_dataset
    series_x, series_y, t = get_series(transactions, labels, look_back)
ValueError: not enough values to unpack (expected 3, got 2)
PyDev console: starting.

Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
